name: Disconnected Readiness
on:
  pull_request:
    branches:
      - main
      - master

jobs:
  check:
    uses: opendatahub-io/disconnected-readiness-scorer/.github/workflows/disconnected-readiness-check.yml@d3092ce4c754a1436e5720f8f85665ee05745b15
    with:
      rules: ""
